on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

name: Quarto Publish Test Branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout repo
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Set up R
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
      
      # Install R deps
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Render quarto doc
      - name: Render Quarto Document
        run: quarto render index.qmd --to html
        env:
          NZ_HOLIDAYS_API_KEY: ${{ secrets.NZ_HOLIDAYS_API_KEY }}

      # Publish to the test branch
      - name: Publish to test branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: test-gh-pages  # Specify the test branch
          publish_dir: _site  # Directory where Quarto outputs the rendered site