on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '30 16 * * *' # 4:30pm UTC ==> 5:30am NZDT/4:30am NZST

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Setup Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # # Install R
      # - name: Install R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: 'renv'
      #     use-public-rspm: true

      # Install R dependencies
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Install the package
      - name: Install TBAWBTurnaroundTimes package
        run: |
          R CMD INSTALL .

      # Render index.qmd and publish to github pages
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NZ_HOLIDAYS_API_KEY: ${{ secrets.NZ_HOLIDAYS_API_KEY }}