on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

name: Quarto Publish Test Branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Quarto Document
        run: quarto render index.qmd --to html

      - name: Rename Rendered File
        run: mv docs/index.html docs/index_test.html # Create a 'test' version of the site.

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NZ_HOLIDAYS_API_KEY: ${{ secrets.NZ_HOLIDAYS_API_KEY }}