name: Run testthat on Pull Request

on:
  pull_request:
    branches:
      - main  # Adjust to the branch you want to monitor

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # Setup
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Install devtools
        run: |
          Rscript -e 'install.packages("devtools")'

      # Run unit tests
      - name: Run testthat
        run: |
          Rscript -e 'library(devtools); devtools::test()'

      # Verify index.qmd render
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        env:
          NZ_HOLIDAYS_API_KEY: ${{ secrets.NZ_HOLIDAYS_API_KEY }}